export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY = 'GET_COMPANY';
export const SET_LOADING = 'SET_LOADING';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';


export const FETCH_DEVIDENTS = 'FETCH_DEVIDENTS';
export const GET_DEVIDENTS = 'GET_DEVIDENTS';